### ISSUE TITLE
Not Allowed to Publish Branch

### ISSUE THREAD

**Issue by mpixton** [stephengodderidge/learn-git#18]
While using Git Desktop, I tried to open a pull request for the repo. Git Desktop told me that I needed to publish the branch to open a pull request. When trying to publish the branch, I got this error message.
 
![image](https://user-images.githubusercontent.com/71086131/94162356-db13e700-fe43-11ea-9bd0-74fa66b5e130.png)

I know its not the top two errors. What is happening?

**Comment by kylelonghurst** [comment]
I haven't used Git Desktop, so I'm not 100% sure. Happy to help you debug the issue though.

Looking at your repository here https://github.com/mpixton/learn-git. It looks like your branch doesn't exist in your remote repository yet. You need to push your changes to your remote repository first before you can open a pull-request.

Running `git push --set-upstream origin my-animal` in the project directory might solve your problem. (You might need to replace `my-animal` with whatever you called your branch)

**Comment by stephengodderidge** [comment]
Yeah ditto to what Kyle said. Also, you might try setting up ssh access to provide authentication. Here's the link for a video tutorial: https://egghead.io/lessons/javascript-how-to-authenticate-with-github-using-ssh

**Comment by mpixton** [comment]
Solved it. Worked great when I didn't use the Desktop client.

**Comment by stephengodderidge** [comment]
Glad to hear!
