### ISSUE TITLE
Please add more details on Step 0

### ISSUE THREAD

**Issue by gillkyle** [stephengodderidge/learn-git#2]
I was trying to follow the steps and got stuck at Step 0 🤔

**Comment by stephengodderidge** [comment]
Bahaha sounds like a personal problem 😂

**Comment by stephengodderidge** [comment]
Very much still a work in progress

**Comment by gillkyle** [comment]
Okay I'll just close because it sounds like the maintainers have a heart of stone. 😊

(hehe)
